project:
  type: website

website:
  title: "pmsims"
  navbar:
    background: primary
    left:
      - href: team.qmd
        text: Team
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    markdown:
      extensions: [fenced-divs]
